import { getFlag } from "./utils";

// Country data with alpha3 and calling codes
export const countryData: {
  [key: string]: {
    name: string;
    alpha3: string;
    callingCode: string;
    flag: string;
  };
} = {
  AD: {
    name: "Andorra",
    alpha3: "AND",
    callingCode: "+376",
    flag: getFlag("AD"),
  },
  AE: {
    name: "United Arab Emirates",
    alpha3: "ARE",
    callingCode: "+971",
    flag: getFlag("AE"),
  },
  AF: {
    name: "Afghanistan",
    alpha3: "AFG",
    callingCode: "+93",
    flag: getFlag("AF"),
  },
  AG: {
    name: "Antigua and Barbuda",
    alpha3: "ATG",
    callingCode: "+1",
    flag: getFlag("AG"),
  },
  AI: {
    name: "Anguilla",
    alpha3: "AIA",
    callingCode: "+1264",
    flag: getFlag("AI"),
  },
  AL: {
    name: "Albania",
    alpha3: "ALB",
    callingCode: "+355",
    flag: getFlag("AL"),
  },
  AM: {
    name: "Armenia",
    alpha3: "ARM",
    callingCode: "+374",
    flag: getFlag("AM"),
  },
  AO: {
    name: "Angola",
    alpha3: "AGO",
    callingCode: "+244",
    flag: getFlag("AO"),
  },
  AQ: {
    name: "Antarctica",
    alpha3: "ATA",
    callingCode: "+672",
    flag: getFlag("AQ"),
  },
  AR: {
    name: "Argentina",
    alpha3: "ARG",
    callingCode: "+54",
    flag: getFlag("AR"),
  },
  AS: {
    name: "American Samoa",
    alpha3: "ASM",
    callingCode: "+1684",
    flag: getFlag("AS"),
  },
  AT: {
    name: "Austria",
    alpha3: "AUT",
    callingCode: "+43",
    flag: getFlag("AT"),
  },
  AU: {
    name: "Australia",
    alpha3: "AUS",
    callingCode: "+61",
    flag: getFlag("AU"),
  },
  AW: {
    name: "Aruba",
    alpha3: "ABW",
    callingCode: "+297",
    flag: getFlag("AW"),
  },
  AX: {
    name: "Åland Islands",
    alpha3: "ALA",
    callingCode: "+358",
    flag: getFlag("AX"),
  },
  AZ: {
    name: "Azerbaijan",
    alpha3: "AZE",
    callingCode: "+994",
    flag: getFlag("AZ"),
  },
  BA: {
    name: "Bosnia and Herzegovina",
    alpha3: "BIH",
    callingCode: "+387",
    flag: getFlag("BA"),
  },
  BB: {
    name: "Barbados",
    alpha3: "BRB",
    callingCode: "+1246",
    flag: getFlag("BB"),
  },
  BD: {
    name: "Bangladesh",
    alpha3: "BGD",
    callingCode: "+880",
    flag: getFlag("BD"),
  },
  BE: {
    name: "Belgium",
    alpha3: "BEL",
    callingCode: "+32",
    flag: getFlag("BE"),
  },
  BF: {
    name: "Burkina Faso",
    alpha3: "BFA",
    callingCode: "+226",
    flag: getFlag("BF"),
  },
  BG: {
    name: "Bulgaria",
    alpha3: "BGR",
    callingCode: "+359",
    flag: getFlag("BG"),
  },
  BH: {
    name: "Bahrain",
    alpha3: "BHR",
    callingCode: "+973",
    flag: getFlag("BH"),
  },
  BI: {
    name: "Burundi",
    alpha3: "BDI",
    callingCode: "+257",
    flag: getFlag("BI"),
  },
  BJ: {
    name: "Benin",
    alpha3: "BEN",
    callingCode: "+229",
    flag: getFlag("BJ"),
  },
  BL: {
    name: "Saint Barthélemy",
    alpha3: "BLM",
    callingCode: "+590",
    flag: getFlag("BL"),
  },
  BM: {
    name: "Bermuda",
    alpha3: "BMU",
    callingCode: "+1441",
    flag: getFlag("BM"),
  },
  BN: {
    name: "Brunei Darussalam",
    alpha3: "BRN",
    callingCode: "+673",
    flag: getFlag("BN"),
  },
  BO: {
    name: "Bolivia, Plurinational State of",
    alpha3: "BOL",
    callingCode: "+591",
    flag: getFlag("BO"),
  },
  BQ: {
    name: "Bonaire, Sint Eustatius and Saba",
    alpha3: "BES",
    callingCode: "+599",
    flag: getFlag("BQ"),
  },
  BR: {
    name: "Brazil",
    alpha3: "BRA",
    callingCode: "+55",
    flag: getFlag("BR"),
  },
  BS: {
    name: "Bahamas",
    alpha3: "BHS",
    callingCode: "+1242",
    flag: getFlag("BS"),
  },
  BT: {
    name: "Bhutan",
    alpha3: "BTN",
    callingCode: "+975",
    flag: getFlag("BT"),
  },
  BV: {
    name: "Bouvet Island",
    alpha3: "BVT",
    callingCode: "+47",
    flag: getFlag("BV"),
  },
  BW: {
    name: "Botswana",
    alpha3: "BWA",
    callingCode: "+267",
    flag: getFlag("BW"),
  },
  BY: {
    name: "Belarus",
    alpha3: "BLR",
    callingCode: "+375",
    flag: getFlag("BY"),
  },
  BZ: {
    name: "Belize",
    alpha3: "BLZ",
    callingCode: "+501",
    flag: getFlag("BZ"),
  },
  CA: { name: "Canada", alpha3: "CAN", callingCode: "+1", flag: getFlag("CA") },
  CC: {
    name: "Cocos (Keeling) Islands",
    alpha3: "CCK",
    callingCode: "+61",
    flag: getFlag("CC"),
  },
  CD: {
    name: "Congo, Democratic Republic of the",
    alpha3: "COD",
    callingCode: "+243",
    flag: getFlag("CD"),
  },
  CF: {
    name: "Central African Republic",
    alpha3: "CAF",
    callingCode: "+236",
    flag: getFlag("CF"),
  },
  CG: {
    name: "Congo",
    alpha3: "COG",
    callingCode: "+242",
    flag: getFlag("CG"),
  },
  CH: {
    name: "Switzerland",
    alpha3: "CHE",
    callingCode: "+41",
    flag: getFlag("CH"),
  },
  CI: {
    name: "Côte d'Ivoire",
    alpha3: "CIV",
    callingCode: "+225",
    flag: getFlag("CI"),
  },
  CK: {
    name: "Cook Islands",
    alpha3: "COK",
    callingCode: "+682",
    flag: getFlag("CK"),
  },
  CL: { name: "Chile", alpha3: "CHL", callingCode: "+56", flag: getFlag("CL") },
  CM: {
    name: "Cameroon",
    alpha3: "CMR",
    callingCode: "+237",
    flag: getFlag("CM"),
  },
  CN: { name: "China", alpha3: "CHN", callingCode: "+86", flag: getFlag("CN") },
  CO: {
    name: "Colombia",
    alpha3: "COL",
    callingCode: "+57",
    flag: getFlag("CO"),
  },
  CR: {
    name: "Costa Rica",
    alpha3: "CRI",
    callingCode: "+506",
    flag: getFlag("CR"),
  },
  CU: { name: "Cuba", alpha3: "CUB", callingCode: "+53", flag: getFlag("CU") },
  CV: {
    name: "Cabo Verde",
    alpha3: "CPV",
    callingCode: "+238",
    flag: getFlag("CV"),
  },
  CW: {
    name: "Curaçao",
    alpha3: "CUW",
    callingCode: "+599",
    flag: getFlag("CW"),
  },
  CX: {
    name: "Christmas Island",
    alpha3: "CXR",
    callingCode: "+61",
    flag: getFlag("CX"),
  },
  CY: {
    name: "Cyprus",
    alpha3: "CYP",
    callingCode: "+357",
    flag: getFlag("CY"),
  },
  CZ: {
    name: "Czechia",
    alpha3: "CZE",
    callingCode: "+420",
    flag: getFlag("CZ"),
  },
  DE: {
    name: "Germany",
    alpha3: "DEU",
    callingCode: "+49",
    flag: getFlag("DE"),
  },
  DJ: {
    name: "Djibouti",
    alpha3: "DJI",
    callingCode: "+253",
    flag: getFlag("DJ"),
  },
  DK: {
    name: "Denmark",
    alpha3: "DNK",
    callingCode: "+45",
    flag: getFlag("DK"),
  },
  DM: {
    name: "Dominica",
    alpha3: "DMA",
    callingCode: "+1",
    flag: getFlag("DM"),
  },
  DO: {
    name: "Dominican Republic",
    alpha3: "DOM",
    callingCode: "+1809",
    flag: getFlag("DO"),
  },
  DZ: {
    name: "Algeria",
    alpha3: "DZA",
    callingCode: "+213",
    flag: getFlag("DZ"),
  },
  EC: {
    name: "Ecuador",
    alpha3: "ECU",
    callingCode: "+593",
    flag: getFlag("EC"),
  },
  EE: {
    name: "Estonia",
    alpha3: "EST",
    callingCode: "+372",
    flag: getFlag("EE"),
  },
  EG: { name: "Egypt", alpha3: "EGY", callingCode: "+20", flag: getFlag("EG") },
  EH: {
    name: "Western Sahara",
    alpha3: "ESH",
    callingCode: "+212",
    flag: getFlag("EH"),
  },
  ER: {
    name: "Eritrea",
    alpha3: "ERI",
    callingCode: "+291",
    flag: getFlag("ER"),
  },
  ES: { name: "Spain", alpha3: "ESP", callingCode: "+34", flag: getFlag("ES") },
  ET: {
    name: "Ethiopia",
    alpha3: "ETH",
    callingCode: "+251",
    flag: getFlag("ET"),
  },
  FI: {
    name: "Finland",
    alpha3: "FIN",
    callingCode: "+358",
    flag: getFlag("FI"),
  },
  FJ: { name: "Fiji", alpha3: "FJI", callingCode: "+679", flag: getFlag("FJ") },
  FK: {
    name: "Falkland Islands (Malvinas)",
    alpha3: "FLK",
    callingCode: "+500",
    flag: getFlag("FK"),
  },
  FM: {
    name: "Micronesia, Federated States of",
    alpha3: "FSM",
    callingCode: "+691",
    flag: getFlag("FM"),
  },
  FO: {
    name: "Faroe Islands",
    alpha3: "FRO",
    callingCode: "+298",
    flag: getFlag("FO"),
  },
  FR: {
    name: "France",
    alpha3: "FRA",
    callingCode: "+33",
    flag: getFlag("FR"),
  },
  GA: {
    name: "Gabon",
    alpha3: "GAB",
    callingCode: "+241",
    flag: getFlag("GA"),
  },
  GB: {
    name: "United Kingdom of Great Britain and Northern Ireland",
    alpha3: "GBR",
    callingCode: "+44",
    flag: getFlag("GB"),
  },
  GD: {
    name: "Grenada",
    alpha3: "GRD",
    callingCode: "+1473",
    flag: getFlag("GD"),
  },
  GE: {
    name: "Georgia",
    alpha3: "GEO",
    callingCode: "+995",
    flag: getFlag("GE"),
  },
  GF: {
    name: "French Guiana",
    alpha3: "GUF",
    callingCode: "+594",
    flag: getFlag("GF"),
  },
  GG: {
    name: "Guernsey",
    alpha3: "GGY",
    callingCode: "+44",
    flag: getFlag("GG"),
  },
  GH: {
    name: "Ghana",
    alpha3: "GHA",
    callingCode: "+233",
    flag: getFlag("GH"),
  },
  GI: {
    name: "Gibraltar",
    alpha3: "GIB",
    callingCode: "+350",
    flag: getFlag("GI"),
  },
  GL: {
    name: "Greenland",
    alpha3: "GRL",
    callingCode: "+299",
    flag: getFlag("GL"),
  },
  GM: {
    name: "Gambia",
    alpha3: "GMB",
    callingCode: "+220",
    flag: getFlag("GM"),
  },
  GN: {
    name: "Guinea",
    alpha3: "GIN",
    callingCode: "+224",
    flag: getFlag("GN"),
  },
  GP: {
    name: "Guadeloupe",
    alpha3: "GLP",
    callingCode: "+590",
    flag: getFlag("GP"),
  },
  GQ: {
    name: "Equatorial Guinea",
    alpha3: "GNQ",
    callingCode: "+240",
    flag: getFlag("GQ"),
  },
  GR: {
    name: "Greece",
    alpha3: "GRC",
    callingCode: "+30",
    flag: getFlag("GR"),
  },
  GS: {
    name: "South Georgia and the South Sandwich Islands",
    alpha3: "SGS",
    callingCode: "+500",
    flag: getFlag("GS"),
  },
  GT: {
    name: "Guatemala",
    alpha3: "GTM",
    callingCode: "+502",
    flag: getFlag("GT"),
  },
  GU: {
    name: "Guam",
    alpha3: "GUM",
    callingCode: "+1671",
    flag: getFlag("GU"),
  },
  GW: {
    name: "Guinea-Bissau",
    alpha3: "GNB",
    callingCode: "+245",
    flag: getFlag("GW"),
  },
  GY: {
    name: "Guyana",
    alpha3: "GUY",
    callingCode: "+592",
    flag: getFlag("GY"),
  },
  HK: {
    name: "Hong Kong",
    alpha3: "HKG",
    callingCode: "+852",
    flag: getFlag("HK"),
  },
  HM: {
    name: "Heard Island and McDonald Islands",
    alpha3: "HMD",
    callingCode: "+672",
    flag: getFlag("HM"),
  },
  HN: {
    name: "Honduras",
    alpha3: "HND",
    callingCode: "+504",
    flag: getFlag("HN"),
  },
  HR: {
    name: "Croatia",
    alpha3: "HRV",
    callingCode: "+385",
    flag: getFlag("HR"),
  },
  HT: {
    name: "Haiti",
    alpha3: "HTI",
    callingCode: "+509",
    flag: getFlag("HT"),
  },
  HU: {
    name: "Hungary",
    alpha3: "HUN",
    callingCode: "+36",
    flag: getFlag("HU"),
  },
  ID: {
    name: "Indonesia",
    alpha3: "IDN",
    callingCode: "+62",
    flag: getFlag("ID"),
  },
  IE: {
    name: "Ireland",
    alpha3: "IRL",
    callingCode: "+353",
    flag: getFlag("IE"),
  },
  IL: {
    name: "Israel",
    alpha3: "ISR",
    callingCode: "+972",
    flag: getFlag("IL"),
  },
  IM: {
    name: "Isle of Man",
    alpha3: "IMN",
    callingCode: "+44",
    flag: getFlag("IM"),
  },
  IN: { name: "India", alpha3: "IND", callingCode: "+91", flag: getFlag("IN") },
  IO: {
    name: "British Indian Ocean Territory",
    alpha3: "IOT",
    callingCode: "+246",
    flag: getFlag("IO"),
  },
  IQ: { name: "Iraq", alpha3: "IRQ", callingCode: "+964", flag: getFlag("IQ") },
  IR: {
    name: "Iran, Islamic Republic of",
    alpha3: "IRN",
    callingCode: "+98",
    flag: getFlag("IR"),
  },
  IS: {
    name: "Iceland",
    alpha3: "ISL",
    callingCode: "+354",
    flag: getFlag("IS"),
  },
  IT: { name: "Italy", alpha3: "ITA", callingCode: "+39", flag: getFlag("IT") },
  JE: {
    name: "Jersey",
    alpha3: "JEY",
    callingCode: "+44",
    flag: getFlag("JE"),
  },
  JM: {
    name: "Jamaica",
    alpha3: "JAM",
    callingCode: "+1876",
    flag: getFlag("JM"),
  },
  JO: {
    name: "Jordan",
    alpha3: "JOR",
    callingCode: "+962",
    flag: getFlag("JO"),
  },
  JP: { name: "Japan", alpha3: "JPN", callingCode: "+81", flag: getFlag("JP") },
  KE: {
    name: "Kenya",
    alpha3: "KEN",
    callingCode: "+254",
    flag: getFlag("KE"),
  },
  KG: {
    name: "Kyrgyzstan",
    alpha3: "KGZ",
    callingCode: "+996",
    flag: getFlag("KG"),
  },
  KH: {
    name: "Cambodia",
    alpha3: "KHM",
    callingCode: "+855",
    flag: getFlag("KH"),
  },
  KI: {
    name: "Kiribati",
    alpha3: "KIR",
    callingCode: "+686",
    flag: getFlag("KI"),
  },
  KM: {
    name: "Comoros",
    alpha3: "COM",
    callingCode: "+269",
    flag: getFlag("KM"),
  },
  KN: {
    name: "Saint Kitts and Nevis",
    alpha3: "KNA",
    callingCode: "+1869",
    flag: getFlag("KN"),
  },
  KP: {
    name: "Korea, Democratic People's Republic of",
    alpha3: "PRK",
    callingCode: "+850",
    flag: getFlag("KP"),
  },
  KR: {
    name: "Korea, Republic of",
    alpha3: "KOR",
    callingCode: "+82",
    flag: getFlag("KR"),
  },
  KW: {
    name: "Kuwait",
    alpha3: "KWT",
    callingCode: "+965",
    flag: getFlag("KW"),
  },
  KY: {
    name: "Cayman Islands",
    alpha3: "CYM",
    callingCode: "+1345",
    flag: getFlag("KY"),
  },
  KZ: {
    name: "Kazakhstan",
    alpha3: "KAZ",
    callingCode: "+7",
    flag: getFlag("KZ"),
  },
  LA: {
    name: "Lao People's Democratic Republic",
    alpha3: "LAO",
    callingCode: "+856",
    flag: getFlag("LA"),
  },
  LB: {
    name: "Lebanon",
    alpha3: "LBN",
    callingCode: "+961",
    flag: getFlag("LB"),
  },
  LC: {
    name: "Saint Lucia",
    alpha3: "LCA",
    callingCode: "+1758",
    flag: getFlag("LC"),
  },
  LI: {
    name: "Liechtenstein",
    alpha3: "LIE",
    callingCode: "+423",
    flag: getFlag("LI"),
  },
  LK: {
    name: "Sri Lanka",
    alpha3: "LKA",
    callingCode: "+94",
    flag: getFlag("LK"),
  },
  LR: {
    name: "Liberia",
    alpha3: "LBR",
    callingCode: "+231",
    flag: getFlag("LR"),
  },
  LS: {
    name: "Lesotho",
    alpha3: "LSO",
    callingCode: "+266",
    flag: getFlag("LS"),
  },
  LT: {
    name: "Lithuania",
    alpha3: "LTU",
    callingCode: "+370",
    flag: getFlag("LT"),
  },
  LU: {
    name: "Luxembourg",
    alpha3: "LUX",
    callingCode: "+352",
    flag: getFlag("LU"),
  },
  LV: {
    name: "Latvia",
    alpha3: "LVA",
    callingCode: "+371",
    flag: getFlag("LV"),
  },
  LY: {
    name: "Libya",
    alpha3: "LBY",
    callingCode: "+218",
    flag: getFlag("LY"),
  },
  MA: {
    name: "Morocco",
    alpha3: "MAR",
    callingCode: "+212",
    flag: getFlag("MA"),
  },
  MC: {
    name: "Monaco",
    alpha3: "MCO",
    callingCode: "+377",
    flag: getFlag("MC"),
  },
  MD: {
    name: "Moldova, Republic of",
    alpha3: "MDA",
    callingCode: "+373",
    flag: getFlag("MD"),
  },
  ME: {
    name: "Montenegro",
    alpha3: "MNE",
    callingCode: "+382",
    flag: getFlag("ME"),
  },
  MF: {
    name: "Saint Martin (French part)",
    alpha3: "MAF",
    callingCode: "+590",
    flag: getFlag("MF"),
  },
  MG: {
    name: "Madagascar",
    alpha3: "MDG",
    callingCode: "+261",
    flag: getFlag("MG"),
  },
  MH: {
    name: "Marshall Islands",
    alpha3: "MHL",
    callingCode: "+692",
    flag: getFlag("MH"),
  },
  MK: {
    name: "North Macedonia",
    alpha3: "MKD",
    callingCode: "+389",
    flag: getFlag("MK"),
  },
  ML: { name: "Mali", alpha3: "MLI", callingCode: "+223", flag: getFlag("ML") },
  MM: {
    name: "Myanmar",
    alpha3: "MMR",
    callingCode: "+95",
    flag: getFlag("MM"),
  },
  MN: {
    name: "Mongolia",
    alpha3: "MNG",
    callingCode: "+976",
    flag: getFlag("MN"),
  },
  MO: {
    name: "Macao",
    alpha3: "MAC",
    callingCode: "+853",
    flag: getFlag("MO"),
  },
  MP: {
    name: "Northern Mariana Islands",
    alpha3: "MNP",
    callingCode: "+1670",
    flag: getFlag("MP"),
  },
  MQ: {
    name: "Martinique",
    alpha3: "MTQ",
    callingCode: "+596",
    flag: getFlag("MQ"),
  },
  MR: {
    name: "Mauritania",
    alpha3: "MRT",
    callingCode: "+222",
    flag: getFlag("MR"),
  },
  MS: {
    name: "Montserrat",
    alpha3: "MSR",
    callingCode: "+1664",
    flag: getFlag("MS"),
  },
  MT: {
    name: "Malta",
    alpha3: "MLT",
    callingCode: "+356",
    flag: getFlag("MT"),
  },
  MU: {
    name: "Mauritius",
    alpha3: "MUS",
    callingCode: "+230",
    flag: getFlag("MU"),
  },
  MV: {
    name: "Maldives",
    alpha3: "MDV",
    callingCode: "+960",
    flag: getFlag("MV"),
  },
  MW: {
    name: "Malawi",
    alpha3: "MWI",
    callingCode: "+265",
    flag: getFlag("MW"),
  },
  MX: {
    name: "Mexico",
    alpha3: "MEX",
    callingCode: "+52",
    flag: getFlag("MX"),
  },
  MY: {
    name: "Malaysia",
    alpha3: "MYS",
    callingCode: "+60",
    flag: getFlag("MY"),
  },
  MZ: {
    name: "Mozambique",
    alpha3: "MOZ",
    callingCode: "+258",
    flag: getFlag("MZ"),
  },
  NA: {
    name: "Namibia",
    alpha3: "NAM",
    callingCode: "+264",
    flag: getFlag("NA"),
  },
  NC: {
    name: "New Caledonia",
    alpha3: "NCL",
    callingCode: "+687",
    flag: getFlag("NC"),
  },
  NE: {
    name: "Niger",
    alpha3: "NER",
    callingCode: "+227",
    flag: getFlag("NE"),
  },
  NF: {
    name: "Norfolk Island",
    alpha3: "NFK",
    callingCode: "+672",
    flag: getFlag("NF"),
  },
  NG: {
    name: "Nigeria",
    alpha3: "NGA",
    callingCode: "+234",
    flag: getFlag("NG"),
  },
  NI: {
    name: "Nicaragua",
    alpha3: "NIC",
    callingCode: "+505",
    flag: getFlag("NI"),
  },
  NL: {
    name: "Netherlands, Kingdom of the",
    alpha3: "NLD",
    callingCode: "+31",
    flag: getFlag("NL"),
  },
  NO: {
    name: "Norway",
    alpha3: "NOR",
    callingCode: "+47",
    flag: getFlag("NO"),
  },
  NP: {
    name: "Nepal",
    alpha3: "NPL",
    callingCode: "+977",
    flag: getFlag("NP"),
  },
  NR: {
    name: "Nauru",
    alpha3: "NRU",
    callingCode: "+674",
    flag: getFlag("NR"),
  },
  NU: { name: "Niue", alpha3: "NIU", callingCode: "+683", flag: getFlag("NU") },
  NZ: {
    name: "New Zealand",
    alpha3: "NZL",
    callingCode: "+64",
    flag: getFlag("NZ"),
  },
  OM: { name: "Oman", alpha3: "OMN", callingCode: "+968", flag: getFlag("OM") },
  PA: {
    name: "Panama",
    alpha3: "PAN",
    callingCode: "+507",
    flag: getFlag("PA"),
  },
  PE: { name: "Peru", alpha3: "PER", callingCode: "+51", flag: getFlag("PE") },
  PF: {
    name: "French Polynesia",
    alpha3: "PYF",
    callingCode: "+689",
    flag: getFlag("PF"),
  },
  PG: {
    name: "Papua New Guinea",
    alpha3: "PNG",
    callingCode: "+675",
    flag: getFlag("PG"),
  },
  PH: {
    name: "Philippines",
    alpha3: "PHL",
    callingCode: "+63",
    flag: getFlag("PH"),
  },
  PK: {
    name: "Pakistan",
    alpha3: "PAK",
    callingCode: "+92",
    flag: getFlag("PK"),
  },
  PL: {
    name: "Poland",
    alpha3: "POL",
    callingCode: "+48",
    flag: getFlag("PL"),
  },
  PM: {
    name: "Saint Pierre and Miquelon",
    alpha3: "SPM",
    callingCode: "+508",
    flag: getFlag("PM"),
  },
  PN: {
    name: "Pitcairn",
    alpha3: "PCN",
    callingCode: "+64",
    flag: getFlag("PN"),
  },
  PR: {
    name: "Puerto Rico",
    alpha3: "PRI",
    callingCode: "+1787",
    flag: getFlag("PR"),
  },
  PS: {
    name: "Palestine, State of",
    alpha3: "PSE",
    callingCode: "+970",
    flag: getFlag("PS"),
  },
  PT: {
    name: "Portugal",
    alpha3: "PRT",
    callingCode: "+351",
    flag: getFlag("PT"),
  },
  PW: {
    name: "Palau",
    alpha3: "PLW",
    callingCode: "+680",
    flag: getFlag("PW"),
  },
  PY: {
    name: "Paraguay",
    alpha3: "PRY",
    callingCode: "+595",
    flag: getFlag("PY"),
  },
  QA: {
    name: "Qatar",
    alpha3: "QAT",
    callingCode: "+974",
    flag: getFlag("QA"),
  },
  RE: {
    name: "Réunion",
    alpha3: "REU",
    callingCode: "+262",
    flag: getFlag("RE"),
  },
  RO: {
    name: "Romania",
    alpha3: "ROU",
    callingCode: "+40",
    flag: getFlag("RO"),
  },
  RS: {
    name: "Serbia",
    alpha3: "SRB",
    callingCode: "+381",
    flag: getFlag("RS"),
  },
  RU: {
    name: "Russian Federation",
    alpha3: "RUS",
    callingCode: "+7",
    flag: getFlag("RU"),
  },
  RW: {
    name: "Rwanda",
    alpha3: "RWA",
    callingCode: "+250",
    flag: getFlag("RW"),
  },
  SA: {
    name: "Saudi Arabia",
    alpha3: "SAU",
    callingCode: "+966",
    flag: getFlag("SA"),
  },
  SB: {
    name: "Solomon Islands",
    alpha3: "SLB",
    callingCode: "+677",
    flag: getFlag("SB"),
  },
  SC: {
    name: "Seychelles",
    alpha3: "SYC",
    callingCode: "+248",
    flag: getFlag("SC"),
  },
  SD: {
    name: "Sudan",
    alpha3: "SDN",
    callingCode: "+249",
    flag: getFlag("SD"),
  },
  SE: {
    name: "Sweden",
    alpha3: "SWE",
    callingCode: "+46",
    flag: getFlag("SE"),
  },
  SG: {
    name: "Singapore",
    alpha3: "SGP",
    callingCode: "+65",
    flag: getFlag("SG"),
  },
  SH: {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    alpha3: "SHN",
    callingCode: "+290",
    flag: getFlag("SH"),
  },
  SI: {
    name: "Slovenia",
    alpha3: "SVN",
    callingCode: "+386",
    flag: getFlag("SI"),
  },
  SJ: {
    name: "Svalbard and Jan Mayen",
    alpha3: "SJM",
    callingCode: "+47",
    flag: getFlag("SJ"),
  },
  SK: {
    name: "Slovakia",
    alpha3: "SVK",
    callingCode: "+421",
    flag: getFlag("SK"),
  },
  SL: {
    name: "Sierra Leone",
    alpha3: "SLE",
    callingCode: "+232",
    flag: getFlag("SL"),
  },
  SM: {
    name: "San Marino",
    alpha3: "SMR",
    callingCode: "+378",
    flag: getFlag("SM"),
  },
  SN: {
    name: "Senegal",
    alpha3: "SEN",
    callingCode: "+221",
    flag: getFlag("SN"),
  },
  SO: {
    name: "Somalia",
    alpha3: "SOM",
    callingCode: "+252",
    flag: getFlag("SO"),
  },
  SR: {
    name: "Suriname",
    alpha3: "SUR",
    callingCode: "+597",
    flag: getFlag("SR"),
  },
  SS: {
    name: "South Sudan",
    alpha3: "SSD",
    callingCode: "+211",
    flag: getFlag("SS"),
  },
  ST: {
    name: "Sao Tome and Principe",
    alpha3: "STP",
    callingCode: "+239",
    flag: getFlag("ST"),
  },
  SV: {
    name: "El Salvador",
    alpha3: "SLV",
    callingCode: "+503",
    flag: getFlag("SV"),
  },
  SX: {
    name: "Sint Maarten (Dutch part)",
    alpha3: "SXM",
    callingCode: "+1721",
    flag: getFlag("SX"),
  },
  SY: {
    name: "Syrian Arab Republic",
    alpha3: "SYR",
    callingCode: "+963",
    flag: getFlag("SY"),
  },
  SZ: {
    name: "Eswatini",
    alpha3: "SWZ",
    callingCode: "+268",
    flag: getFlag("SZ"),
  },
  TC: {
    name: "Turks and Caicos Islands",
    alpha3: "TCA",
    callingCode: "+1649",
    flag: getFlag("TC"),
  },
  TD: { name: "Chad", alpha3: "TCD", callingCode: "+235", flag: getFlag("TD") },
  TF: {
    name: "French Southern Territories",
    alpha3: "ATF",
    callingCode: "+262",
    flag: getFlag("TF"),
  },
  TG: { name: "Togo", alpha3: "TGO", callingCode: "+228", flag: getFlag("TG") },
  TH: {
    name: "Thailand",
    alpha3: "THA",
    callingCode: "+66",
    flag: getFlag("TH"),
  },
  TJ: {
    name: "Tajikistan",
    alpha3: "TJK",
    callingCode: "+992",
    flag: getFlag("TJ"),
  },
  TK: {
    name: "Tokelau",
    alpha3: "TKL",
    callingCode: "+690",
    flag: getFlag("TK"),
  },
  TL: {
    name: "Timor-Leste",
    alpha3: "TLS",
    callingCode: "+670",
    flag: getFlag("TL"),
  },
  TM: {
    name: "Turkmenistan",
    alpha3: "TKM",
    callingCode: "+993",
    flag: getFlag("TM"),
  },
  TN: {
    name: "Tunisia",
    alpha3: "TUN",
    callingCode: "+216",
    flag: getFlag("TN"),
  },
  TO: {
    name: "Tonga",
    alpha3: "TON",
    callingCode: "+676",
    flag: getFlag("TO"),
  },
  TR: {
    name: "Türkiye",
    alpha3: "TUR",
    callingCode: "+90",
    flag: getFlag("TR"),
  },
  TT: {
    name: "Trinidad and Tobago",
    alpha3: "TTO",
    callingCode: "+1868",
    flag: getFlag("TT"),
  },
  TV: {
    name: "Tuvalu",
    alpha3: "TUV",
    callingCode: "+688",
    flag: getFlag("TV"),
  },
  TW: {
    name: "Taiwan, Province of China",
    alpha3: "TWN",
    callingCode: "+886",
    flag: getFlag("TW"),
  },
  TZ: {
    name: "Tanzania, United Republic of",
    alpha3: "TZA",
    callingCode: "+255",
    flag: getFlag("TZ"),
  },
  UA: {
    name: "Ukraine",
    alpha3: "UKR",
    callingCode: "+380",
    flag: getFlag("UA"),
  },
  UG: {
    name: "Uganda",
    alpha3: "UGA",
    callingCode: "+256",
    flag: getFlag("UG"),
  },
  UM: {
    name: "United States Minor Outlying Islands",
    alpha3: "UMI",
    callingCode: "+1",
    flag: getFlag("UM"),
  },
  US: {
    name: "United States of America",
    alpha3: "USA",
    callingCode: "+1",
    flag: getFlag("US"),
  },
  UY: {
    name: "Uruguay",
    alpha3: "URY",
    callingCode: "+598",
    flag: getFlag("UY"),
  },
  UZ: {
    name: "Uzbekistan",
    alpha3: "UZB",
    callingCode: "+998",
    flag: getFlag("UZ"),
  },
  VA: {
    name: "Holy See",
    alpha3: "VAT",
    callingCode: "+379",
    flag: getFlag("VA"),
  },
  VC: {
    name: "Saint Vincent and the Grenadines",
    alpha3: "VCT",
    callingCode: "+1784",
    flag: getFlag("VC"),
  },
  VE: {
    name: "Venezuela, Bolivarian Republic of",
    alpha3: "VEN",
    callingCode: "+58",
    flag: getFlag("VE"),
  },
  VG: {
    name: "Virgin Islands (British)",
    alpha3: "VGB",
    callingCode: "+1284",
    flag: getFlag("VG"),
  },
  VI: {
    name: "Virgin Islands (U.S.)",
    alpha3: "VIR",
    callingCode: "+1340",
    flag: getFlag("VI"),
  },
  VN: {
    name: "Viet Nam",
    alpha3: "VNM",
    callingCode: "+84",
    flag: getFlag("VN"),
  },
  VU: {
    name: "Vanuatu",
    alpha3: "VUT",
    callingCode: "+678",
    flag: getFlag("VU"),
  },
  WF: {
    name: "Wallis and Futuna",
    alpha3: "WLF",
    callingCode: "+681",
    flag: getFlag("WF"),
  },
  WS: {
    name: "Samoa",
    alpha3: "WSM",
    callingCode: "+685",
    flag: getFlag("WS"),
  },
  YE: {
    name: "Yemen",
    alpha3: "YEM",
    callingCode: "+967",
    flag: getFlag("YE"),
  },
  YT: {
    name: "Mayotte",
    alpha3: "MYT",
    callingCode: "+262",
    flag: getFlag("YT"),
  },
  ZA: {
    name: "South Africa",
    alpha3: "ZAF",
    callingCode: "+27",
    flag: getFlag("ZA"),
  },
  ZM: {
    name: "Zambia",
    alpha3: "ZMB",
    callingCode: "+260",
    flag: getFlag("ZM"),
  },
  ZW: {
    name: "Zimbabwe",
    alpha3: "ZWE",
    callingCode: "+263",
    flag: getFlag("ZW"),
  },
};

// Simple name lookup map for backwards compatibility
export const countries: { [key: string]: string } = Object.keys(
  countryData
).reduce((acc, code) => {
  acc[code] = countryData[code].name;
  return acc;
}, {} as { [key: string]: string });

// Pre-computed arrays for better performance
export const countryCodes = Object.keys(countryData);
export const countryNames = Object.values(countryData).map((c) => c.name);

export {
  getAllCountries,
  getAlpha3Code,
  getCallingCode,
  getCountryByCode,
  getCountryFlag,
  getCountryName,
  searchCountries,
  isValidCountryCode,
  isValidCallingCode,
  getCountriesByCallingCode
} from "./utils";
export {type Country, type CountryCode} from './types'
